# Generated by Django 3.1.14 on 2022-04-20 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignmentTemplate',
            field=models.FileField(null=True, upload_to='assignment_templates', validators=[django.core.validators.FileExtensionValidator(['jar'])]),
        ),
        migrations.AddField(
            model_name='assignment',
            name='solutionFile',
            field=models.FileField(null=True, upload_to='assignment_solutions', validators=[django.core.validators.FileExtensionValidator(['jar'])]),
        ),
    ]
