# Generated by Django 3.1.14 on 2022-04-27 09:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='memory',
            new_name='memoryLimit',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='time',
            new_name='timeLimit',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='inputDescription',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='outputDescription',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='solutionFile',
            field=models.FileField(null=True, upload_to='assignment_solutions', validators=[django.core.validators.FileExtensionValidator(['jar'])]),
        ),
        migrations.CreateModel(
            name='UserTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('memory', models.PositiveSmallIntegerField()),
                ('time', models.PositiveSmallIntegerField()),
                ('error', models.TextField()),
                ('output_label', models.CharField(max_length=200)),
                ('testcase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.testcase')),
                ('userassignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userassignment')),
            ],
        ),
    ]
