# Generated by Django 3.2.9 on 2022-01-01 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='shortTitle',
            field=models.CharField(default='P1', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
