# Generated by Django 4.0.4 on 2022-06-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.CharField(max_length=50),
        ),
    ]
