# Generated by Django 3.2.9 on 2022-01-01 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220101_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tags',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='tags',
        ),
        migrations.AddField(
            model_name='assignment',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tag'),
        ),
        migrations.AlterField(
            model_name='course',
            name='shortTitle',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
