# Generated by Django 3.1.14 on 2022-04-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220420_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assignment'),
        ),
    ]
