# Generated by Django 3.1.14 on 2022-04-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220427_1154'),
        ('app', '0002_auto_20220427_0955'),
    ]

    operations = [
    ]
