# Generated by Django 4.0 on 2022-01-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220101_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='shortTitle',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
