# Generated by Django 3.1.14 on 2022-04-22 16:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220420_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jar', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jar'])])),
                ('percentage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.assignment')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentassignment',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='studentassignment',
            name='student',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='students',
            new_name='newusers',
        ),
        migrations.AddField(
            model_name='newuser',
            name='courses',
            field=models.ManyToManyField(to='app.Course'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='lastName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentAssignment',
        ),
        migrations.AddField(
            model_name='userassignment',
            name='newuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
