# Generated by Django 3.1.14 on 2022-04-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20220427_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='inputDescription',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='outputDescription',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='usertestcase',
            name='testcase',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.testcase'),
        ),
        migrations.AlterField(
            model_name='usertestcase',
            name='userassignment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userassignment'),
        ),
    ]
