# Generated by Django 4.0.4 on 2022-06-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_studentanswer_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentquiz',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentquiz',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
