# Generated by Django 3.1.14 on 2022-04-25 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220423_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='solutionFile',
            field=models.FileField(upload_to='assignment_solutions', validators=[django.core.validators.FileExtensionValidator(['jar'])]),
        ),
    ]
