# Generated by Django 3.2.9 on 2022-01-01 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220101_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='grade',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.test'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.assignment'),
        ),
    ]
