# Generated by Django 3.1.14 on 2022-04-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220422_1813'),
        ('app', '0004_auto_20220425_2349'),
    ]

    operations = [
    ]
