# Generated by Django 3.2.9 on 2022-01-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220101_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='testCaseCount',
        ),
        migrations.AddField(
            model_name='testcase',
            name='time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='tags',
        ),
        migrations.AddField(
            model_name='assignment',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
