# Generated by Django 3.1.14 on 2022-04-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220427_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestcase',
            name='error',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usertestcase',
            name='memory',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usertestcase',
            name='output_label',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usertestcase',
            name='time',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
