# Generated by Django 3.2.9 on 2022-01-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220101_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='isAnswerVisible',
            new_name='isSolutionVisible',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='answer',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
