# Generated by Django 3.1.14 on 2022-06-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220515_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestcase',
            name='user_output',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
