# Generated by Django 4.0.4 on 2022-05-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_answer_id_alter_assignment_id_alter_course_id_and_more'),
        ('app', '0007_auto_20220515_1547'),
    ]

    operations = [
    ]
