# Generated by Django 4.0.4 on 2022-05-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20220516_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestcase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
