# Generated by Django 3.2.9 on 2022-01-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_assignment_percentage_alter_course_shorttitle'),
        ('app', '0008_alter_course_students'),
    ]

    operations = [
    ]
