# Generated by Django 4.0.4 on 2022-05-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_studentanswer_answer_studentanswer_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questionNum',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='app.quiz'),
        ),
    ]
