# Generated by Django 3.2.9 on 2022-02-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_studentassignment_jar'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='inputDescription',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='outputDescription',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='time',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
