# Generated by Django 3.2.9 on 2022-02-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220226_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='inputDescription',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='outputDescription',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
