# Generated by Django 3.2.9 on 2022-02-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220226_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='isVisible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.assignment'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='hint',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
