# Generated by Django 3.2.12 on 2022-03-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220302_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='endtDate',
            new_name='endDate',
        ),
    ]
