# Generated by Django 3.2.12 on 2022-04-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220403_1828'),
        ('app', '0018_rename_endtdate_test_enddate'),
    ]

    operations = [
    ]
