# Generated by Django 4.0.4 on 2022-06-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_studentanswer_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questionNum',
        ),
        migrations.AddField(
            model_name='studentquiz',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
