# Generated by Django 3.1.14 on 2022-04-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20220422_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='test',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='student',
            field=models.ManyToManyField(to='app.Student'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ManyToManyField(to='app.Answer')),
                ('question', models.ManyToManyField(to='app.Question')),
                ('student', models.ManyToManyField(to='app.Student')),
            ],
        ),
    ]
