name: Meeting reminder

on:
  schedule:
    - cron: "45 16 * * 5" #run this action every friday at 16:45


jobs:
  action:
    runs-on: ubuntu-latest
    steps:
    - name: Send meeting reminder email
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: rijeka.riteh.hr
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{secrets.EMAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.EMAIL_PASSWORD}}
        # Required mail subject:
        subject: Project Meeting Reminder
        # Required recipients' addresses:
        to: bornaparo@gmail.com,luka.skrlj6@gmail.com,kristijanfajdeticcro@gmail.com,anthea.zubcic@gmail.com
        from: no-reply
        secure: true
        # Optional plain body:
        body: Meeting for project in subject Software Engineering starts in 15 minutes (17:00).
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        priority: normal
